// Generated by CoffeeScript 1.12.7
(function() {
  var ScoreTracker, roundPercentage,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ScoreTracker = (function() {
    function ScoreTracker(scoreInHtml) {
      this.scoreInHtml = scoreInHtml;
      this.decisiveWinner = bind(this.decisiveWinner, this);
      this.updateScores = bind(this.updateScores, this);
      this.recordGame = bind(this.recordGame, this);
      this.games = 0;
      this.players = [];
      this.scores = [];
      this.proportions = [];
      this.elementWidth = 940;
    }

    ScoreTracker.prototype.reset = function() {
      this.games = 0;
      this.players = [];
      this.scores = [];
      this.proportions = [];
      if (this.scoreInHtml) {
        return this.updateScoresOnPage();
      }
    };

    ScoreTracker.prototype.setPlayers = function(players) {
      var player;
      if (players.join() !== this.players.join()) {
        this.reset();
        this.players = players;
        this.scores = (function() {
          var j, len, ref, results;
          ref = this.players;
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            player = ref[j];
            results.push(0);
          }
          return results;
        }).call(this);
        return this.proportions = (function() {
          var j, len, ref, results;
          ref = this.players;
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            player = ref[j];
            results.push(0);
          }
          return results;
        }).call(this);
      }
    };

    ScoreTracker.prototype.incrementPlayerScore = function(player, inc) {
      var i, j, ref, results;
      results = [];
      for (i = j = 0, ref = this.players.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (this.players[i] === player) {
          this.scores[i] += inc;
          break;
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    ScoreTracker.prototype.getPlayerScore = function(player) {
      var i, j, ref;
      for (i = j = 0, ref = this.players.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (this.players[i] === player) {
          return this.scores[i];
        }
      }
    };

    ScoreTracker.prototype.recordGame = function(state) {
      var j, len, winner, winners;
      winners = state.getWinners();
      for (j = 0, len = winners.length; j < len; j++) {
        winner = winners[j];
        this.incrementPlayerScore(winner, 1.0 / winners.length);
      }
      this.games += 1;
      return this.updateScores();
    };

    ScoreTracker.prototype.errorMargin = function() {
      return 1.5 / Math.sqrt(this.games);
    };

    ScoreTracker.prototype.updateScores = function() {
      var score;
      return this.proportions = (function() {
        var j, len, ref, results;
        ref = this.scores;
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          score = ref[j];
          results.push(score / this.games);
        }
        return results;
      }).call(this);
    };

    ScoreTracker.prototype.decisiveWinner = function() {
      var i, j, ref;
      for (i = j = 0, ref = this.players.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (this.proportions[i] - this.errorMargin() > 1 / this.scores.length) {
          return this.players[i];
        }
      }
      return null;
    };

    ScoreTracker.prototype.updateScoresOnPage = function() {
      var certain1, certain2, err, i, j, scoreHtml, uncertain1, uncertain2;
      if (this.games === 0) {
        $('#win-p1-certain').width(10);
        $('#win-p2-certain').width(10);
        $('#win-p1-uncertain').width(469);
        $('#win-p2-uncertain').width(469);
        $('#score-p1').html('');
        $('#score-p2').html('');
        return;
      }
      err = this.errorMargin();
      certain1 = this.proportions[0] - err;
      if (certain1 < 0) {
        certain1 = 0;
      }
      certain2 = this.proportions[1] - err;
      if (certain2 < 0) {
        certain2 = 0;
      }
      uncertain1 = this.proportions[0];
      if (uncertain1 > 1) {
        uncertain1 = 1;
      }
      uncertain2 = this.proportions[1];
      if (uncertain2 > 1) {
        uncertain2 = 1;
      }
      $('#win-p1-certain').width(this.elementWidth * certain1);
      $('#win-p2-certain').width(this.elementWidth * certain2);
      $('#win-p1-uncertain').width(this.elementWidth * uncertain1 - 1);
      $('#win-p2-uncertain').width(this.elementWidth * uncertain2 - 1);
      scoreHtml = [null, null];
      for (i = j = 0; j <= 1; i = ++j) {
        scoreHtml[i] = "<strong>" + this.players[i] + "</strong>:\n" + this.scores[i] + " wins (" + (roundPercentage(this.proportions[i])) + "%)";
      }
      $('#score-p1').html(scoreHtml[0]);
      return $('#score-p2').html(scoreHtml[1]);
    };

    return ScoreTracker;

  })();

  roundPercentage = function(num) {
    return (num * 100).toFixed(1);
  };

  this.ScoreTracker = ScoreTracker;

}).call(this);
